### ISSUE TITLE
Compilation and other issues(?)

### ISSUE THREAD

**Issue by harish0201** [ekg/wfmash#1]
Hi!

I was planning to perform an alignment of the genome that I'm working on currently (bird and an insect) for which I need to identify segmental duplications.

If I'm understanding the ReadMe correctly, I should be able to perform base level alignments so that I can extract the boundaries of the alignments and bin/extract those to form the regions of interest. 

Would you think that I can use wfmash for this purpose?

Also, irrespective of this question, I wanted to mess about a bit and learn about Pangenomes, but I'm running into compilation issues, for which I have attached a screenshot:
![image](https://user-images.githubusercontent.com/9093815/93376408-2e4fcd80-f877-11ea-96fd-e7af68196e66.png)

My GCC is 9.3.0, so I think that it should not be an issue? gsl-config --version shows it to be 2.5.

I tried this on other systems as well, but the issue remains the same.

**Comment by ekg** [comment]
Hey! The integration isn't quite complete, but you should be able to use it soon. There are currently some major problems with the mapping cigar parsing. 

If you just want an approximate mapping you can use edyeet -m (I think) or wfmash -m.

To build you need to ./bootstrap and then ./configure. That will get you a makefile.

**Comment by harish0201** [comment]
Hi!

Sorry for the delayed reply! I didn't get any notifications from GitHub.

I think I'll stick with edyeet as I was only able to compile that, wfmash still shows me error during compilation.

Sorry for the trouble!

**Comment by jelber2** [comment]
I seem to be getting the same problem as @harish0201? Using Ubuntu 16.04.7 LTS. Maybe there is something wrong with my system and `./configure` not making a `Makefile` in the `src/common/WFA` directory?

**Comment by ekg** [comment]
What's the compilation error?

**Comment by jelber2** [comment]
VMUDOMAIN\elbersj@klivv-genetics:/genetics/elbers/wfmash-0.1$ ./bootstrap.sh 
    VMUDOMAIN\elbersj@klivv-genetics:/genetics/elbers/wfmash-0.1$ ./configure 
    checking for g++... g++
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking how to run the C++ preprocessor... g++ -E
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking zlib.h usability... yes
    checking zlib.h presence... yes
    checking for zlib.h... yes
    checking gsl/gsl_cdf.h usability... yes
    checking gsl/gsl_cdf.h presence... yes
    checking for gsl/gsl_cdf.h... yes
    configure: creating ./config.status
    config.status: creating Makefile
    VMUDOMAIN\elbersj@klivv-genetics:/genetics/elbers/wfmash-0.1$ make
    cd src/common/WFA && make
    make[1]: Entering directory '/genetics/elbers/wfmash-0.1/src/common/WFA'
    make[1]: *** No targets specified and no makefile found. Stop.
    make[1]: Leaving directory '/genetics/elbers/wfmash-0.1/src/common/WFA'
    Makefile:15: recipe for target 'src/common/WFA/build/libwfa.a' failed
    make: *** [src/common/WFA/build/libwfa.a] Error 2

**Comment by jelber2** [comment]
It appears that there is no Makefile generated in the directory `/genetics/elbers/wfmash-0.1/src/common/WFA` by `configure`?

**Comment by ekg** [comment]
Thanks! You must be the first ones to compile this. I should have an
automated check.

The WFA Makefile was excluded from my commits due to a line in the
.gitignore.

**Comment by ekg** [comment]
My local tree was building fine, but for reasons I'm still debugging the linking isn't working properly when I build from the public repo.

**Comment by ekg** [comment]
This should be resolved now. Please let me know if it's still a problem on your systems.

**Comment by jelber2** [comment]
It compiles now! Thanks!

**Comment by niemasd** [comment]
Just a heads up that cloning the repo compiles fine, but I get the exact same error if I try to compile from the release:

https://github.com/ekg/wfmash/releases/tag/v0.1

You may want to delete and re-release with the compile fix :-)

**Comment by harish0201** [comment]
Huh, there were tons of dependency issues (gsl was throwing a fit) so I
basically gave up.

I should probably learn to reread error messages.

It's compiling on my system as well.

**Comment by ekg** [comment]
I'll make another release. The title will be something like "other people can compile it" 🙃😅
