### ISSUE TITLE
Provide version number in --help or add new --version argument

### ISSUE THREAD

**Issue by heuermh** [ekg/wfmash#106]
For https://github.com/nf-core/pangenome/issues/70 and https://github.com/nf-core/modules/issues/1132 it would be desireable to have `wfmash` provide its version number in the `--help` output or preferably in a new `--version` argument.

**Comment by AndreaGuarracino** [comment]
Hi @heuermh, such a feature was recently added in #105 (`wfmash --version`). Soon it will land in `bioconda` too.
