### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by brunocontrerasmoreira** [ekg/wfmash#110]
Hi @AndreaGuarracino ,
I have been compiling from cloned source the last few days and running the following test with no trouble:

    /wfmash/build/bin/wfmash -p 95 -s 3000 -t 4 Oryza_indica.chr1.fna Oryza_nivara.chr1.fna

However, today it fails (core dump) and I wonder whether that might be due to changes in the source made today:

    [wfmash::map] Reference = [Oryza_indica.chr1.fna]
    [wfmash::map] Query = [Oryza_nivara.chr1.fna]
    [wfmash::map] Kmer size = 17
    [wfmash::map] Window size = 23
    [wfmash::map] Segment length = 3000 (read split allowed)
    [wfmash::map] Block length min = 9000
    [wfmash::map] Alphabet = DNA
    [wfmash::map] Percentage identity threshold = 95%
    [wfmash::map] Mapping output file = /home/contrera/plant-scripts/pangenes/wfmash-ZAgVkE
    [wfmash::map] Filter mode = 1 (1 = map, 2 = one-to-one, 3 = none)
    [wfmash::map] Execution threads  = 4
    [wfmash::skch::Sketch::build] minimizers picked from reference = 3820799
    [wfmash::skch::Sketch::index] unique minimizers = 3117417
    [wfmash::skch::Sketch::computeFreqHist] Frequency histogram of minimizers = (1, 2763195) ... (1316, 1)
    [wfmash::skch::Sketch::computeFreqHist] With threshold 0.001%, ignore minimizers occurring >= 198 times during lookup.
    [wfmash::map] time spent computing the reference index: 4.42687 sec
    terminate called after throwing an instance of 'std::invalid_argument'
     what():  stoi

Hope this helps,
Bruno

**Comment by AndreaGuarracino** [comment]
Hi @brunocontrerasmoreira,
thank you for reporting the problem. It doesn't seem related to what I committed today. You could confirm that by trying a previous commit:

```
git clone --recursive https://github.com/ekg/wfmash.git
cd wfmash
git checkout 66ef26289cf91fce9dd9ec2d200b73ed9c8606e7
cmake -H. -Bbuild && cmake --build build -- -j 3
```

I am wondering if it is related to the input content. May I ask you to share the input? or to show me the names of the sequences in the 2 FASTA files? There should be the `Oryza_indica.chr1.fna.fai` and `Oryza_nivara.chr1.fna.fai` files in the same directory, that should be pretty small.

**Comment by AndreaGuarracino** [comment]
Also sharing the `/home/contrera/plant-scripts/pangenes/wfmash-ZAgVkE` file could be helpful.

**Comment by brunocontrerasmoreira** [comment]
You are right @AndreaGuarracino , input format might also be the issue. These are FASTA files with a single chromosome. You'll see the real names are a bit longer. I attached them plius the indexes and the latest wfmash- file. Many thanks for your help!

[files.zip](https://github.com/ekg/wfmash/files/7870900/files.zip)

**Comment by AndreaGuarracino** [comment]
@brunocontrerasmoreira, I've understood the two problems with your FASTA files:

- the headers contain spaces, so the corresponding sequence names in the FAI indexes are truncated. For example:

```
grep '>' _Oryza_nivara_v1.chr1.fna
>1 dna:chromosome chromosome:Oryza_nivara_v1.0:1:1:42845077:1 REF

head _Oryza_nivara_v1.chr1.fna.fai 
1	42845077	67	60	62
```

- the FASTA files contain the `CTRL-M (^M)` characters at the end of each row:

```
cat -A _Oryza_nivara_v1.chr1.fna | head -n 5
>1 dna:chromosome chromosome:Oryza_nivara_v1.0:1:1:42845077:1 REF^M$
TCTTAGAGACTATTTGGCGCGCGGTGATTTTACCTACATGAGGTATTTTTGGTGATTGAT^M$
GTTTTTATGCTACAAGAGGAAATTCGTCTCAAGGTGGAGATTGTTAAATATGTTATCCGA^M$
ATTTTGGGCCCACAATATATTCGGATTAGTTTCCTAGTAGGAGTCCTATTAGGTGTCTTT^M$
CTTTTATCCCCTATATATACTCTTGTAAGCCGTACGGGAAGGGGTGGCGTTCCCATTGTG^M$
```

To 'sanitize' the FASTA files with a single command line, I would suggest using [fastaix](https://github.com/ekg/fastix). It will add a prefix to each header and remove the `^M` at the end of the rows. For example:

```
fastix -p Oindica# _Oryza_indica.ASM465v1.chr1.fna > Oindica.fa
fastix -p Onivara# _Oryza_nivara_v1.chr1.fna > Onivara.fa
samtools faidx Oindica.fa 
samtools faidx Onivara.fa 

wfmash -p 95 -s 3000 -t 4 Oindica.fa Onivara.fa > x.paf
head x.paf
Onivara#1	42845077	345000	378000	+	Oindica#1	47283185	459486	492599	32268	33113	14	gi:f:0.99688	bi:f:0.955381	md:f:0.995491	wt:i:59	pt:i:86	aa:i:1	ap:i:1	cg:Z:58=1X3=1X207=1X641=1X524=1X288=1X13=1X244=1X789=2I153=1X944=1X31=1X227=1X932=1X1324=1X593=1D1196=1I99=1X133=1X34=6I90=1X233=1X245=1X31=1X117=1X203=1X301=38I63=1X515=2D356=1X69=1X163=1I556=1X479=1X45=1X1=1D2=1X147=1X2226=1X41=22I180=1D31=1D486=1I448=1X1102=1X1235=1X194=1X44=1X241=1X117=1X40=2I68=1X9=4D89=1X147=1X22=1I90=1X36=1X158=2D91=11D355=1X117=1I151=6I413=1D2914=1X245=1X211=1X94=6D343=1X67=1I17=1X352=1X116=1X601=1X7=1X23=1X10=25D8=1X577=14D199=1X351=1I299=1X1131=2D34=1X113=1X20=1X133=1I927=1X37=1X258=1X87=1X65=1I22=1X28=1X30=1X292=1X446=1X365=1I564=1X1099=576I2=704D1=
Onivara#1	42845077	291000	342328	+	Oindica#1	47283185	398401	448398	49707	51328	15	gi:f:0.996712	bi:f:0.965184	md:f:0.99386	wt:i:100	pt:i:79	aa:i:14921	ap:i:447	cg:Z:94=27D16=11I451=1X1173=2X13=1X390=1X179=1X380=2I1331=1X7=1X120=1X84=1X24=1X41=1X17=1X41=1X305=1X11=1X73=1X20=1X19=1X1=1X79=1X176=1X32=1I275=2D1=4I129=1X6=1X1=1X84=1X17=1X122=1143I39=1X18=1X385=1X81=1X7=1X71=1X81=1X255=1X30=1X160=1X19=1X180=1X54=1X56=2X9=1X78=1X14=1X1353=16I238=1X407=1X1=4I71=3D268=1X496=1X147=1X149=1I116=33I19=1X407=1X342=1X1234=16D15=1X52=1X124=1D6=1D8=1X748=9I212=1X570=1I7=1I75=1X47=2D64=1X259=1X33=3D4=4I50=1X160=1X43=2I88=1X32=1D105=1D54=1X90=1X51=1X136=1X48=1X164=1X33=1X58=1D356=1X91=1X380=1D24=1X4=1I4=1I24=1I14=1X65=1D218=1X97=1X287=1X67=1X1540=56D550=1D17=1X935=1X137=1X1000=1X695=1X815=1X41=1X367=1X76=1X140=1X794=1I28=1I264=1X1891=1X921=1X311=1D985=1I370=1X86=1X325=1D1176=1X1292=1I1030=1X362=1X1154=1X634=1D262=1X488=1X50=1I327=1X901=2I920=1X5=259I50D872=1X1584=1X13=2D445=1X1048=1X240=1I701=1X311=1X226=1X349=1X325=1X171=1X731=1X293=1X743=1X322=1I69=1X59=1X473=2X2379=
```

Please update `wfmash` to the current `master` and let me know if everything is okay now.

**Comment by brunocontrerasmoreira** [comment]
Hi @AndreaGuarracino , sorry for the ^M chars, those were not part of the original file but (I think) were added while uploading them to GitHub from a Windows laptop.
Anyway, I can confirm the latest version on master handles correctly the .fai & FASTA files in my example, thanks so much,
Bruno
