### ISSUE TITLE
Unbundle atomic_queue

### ISSUE THREAD

**Issue by arunisaac** [ekg/wfmash#123]
I am working on a RISC-V port for wfmash. One of the blockers is the version of atomic_queue bundled with wfmash. It is an old version that does not support RISC-V, whereas the newest version of atomic_queue does support RISC-V. atomic-queue is now a Guix package. See https://git.savannah.gnu.org/cgit/guix.git/commit/?id=61b4b6aea29b24f4a1c6af7d8f4e1c416ab41c86 It would be best to unbundle atomic_queue and depend on it as an external dependency. This also has the added advantage that wfmash would seamlessly benefit from updates to atomic_queue.

**Comment by AndreaGuarracino** [comment]
Hi @arunisaac, at this stage we are still avoiding the git module system to ease the development, but I agree with you that in the long run, it would be better to unbundle the dependencies.

I've just updated the `atomic_queue` dependency (#129). Can you please check if this solves your problem?

**Comment by arunisaac** [comment]
I confirm that this works. Thank you!
