### ISSUE TITLE
Do not check for x86_64 in src/common/dset64.hpp

### ISSUE THREAD

**Issue by arunisaac** [ekg/wfmash#124]
I am working on a RISC-V port of wfmash. `src/common/dset64.hpp` has preprocessor checks to ensure that we are compiling for x86_64. If you could remove that check, or relax it to include RISC-V, that would be great.

Thank you!

**Comment by AndreaGuarracino** [comment]
Does it mean that the preprocessor check can stay?

**Comment by arunisaac** [comment]
No, the preprocessor check must still go. I think @Millak means that the build is successful on aarch64 and riscv64 when the preprocessor check has been removed, and that there is no other CPU-specific code that needs to be ported.

**Comment by AndreaGuarracino** [comment]
@arunisaac and @Millak, I have removed the preprocessor check. If we have broken something, I will come knocking on your doors :mask:

**Comment by arunisaac** [comment]
Yes, please! ;-) Thanks!
