### ISSUE TITLE
SAM output

### ISSUE THREAD

**Issue by niemasd** [ekg/wfmash#3]
It would be great if there was an option to output the alignment in the SAM format instead of PAF (e.g. Minimap2's ``-a`` flag)

**Comment by ekg** [comment]
This should be possible, but it will require merging the segment mappings. It is possible to locally repeat a piece of the target, which will have to be removed from the alignment or will break the cigar, as there is no operator to indicate going backwards in the target.

**Comment by ekg** [comment]
Also, the cigar for a SAM record of the alignment of two ~10mb sequences is going to be very big!

**Comment by niemasd** [comment]
I plan on using this to align viral genomes, so my genomes are fortunately only 30 KB :smile:

**Comment by ekg** [comment]
I've completed the first steps required to support this: https://github.com/ekg/wflign/pull/4

**Comment by ekg** [comment]
The SAM format requires a header with the reference sequences, correct? I'll have to implement that here in wfmash.

**Comment by niemasd** [comment]
This is excellent news! Regarding the reference genome, yes, the header generally includes the filename of the reference genome. I *believe* the header is *technically* optional, though (but would be good to include for completeness)

**Comment by ekg** [comment]
wfmash now makes a single PAF record per mapping, with a single merged cigar representing the whole alignment.

SAM will take a little more work. I am a little confused about the requirements. Is there a way report alignments of _parts_ of sequences in PAF? I don't know if it will make sense to do a single "primary" mapping for each alignment and exclude the others.

FWIW, if the sequences are aligned without splits, then the transformation from PAF to SAM will be trivial. If the sequences we're mapping are in the 10-200kb range then it's probably OK to use the -N flag to do this, or to require -N when making SAM. Thoughts?

**Comment by niemasd** [comment]
> wfmash now makes a single PAF record per mapping, with a single merged cigar representing the whole alignment.

Thank you for implementing this! Having a single merged CIGAR string is super helpful.

> SAM will take a little more work. I am a little confused about the requirements. Is there a way report alignments of parts of sequences in PAF? I don't know if it will make sense to do a single "primary" mapping for each alignment and exclude the others.

I'm not too sure, I'm not very knowledgeable about the PAF format

> FWIW, if the sequences are aligned without splits, then the transformation from PAF to SAM will be trivial. If the sequences we're mapping are in the 10-200kb range then it's probably OK to use the -N flag to do this, or to require -N when making SAM. Thoughts?

Yeah I think that makes sense. Requiring `-N` when making SAM seems like a fair requirement for the sake of clarity/consistency

**Comment by ekg** [comment]
A word of caution: I've found a bug in the cigar merging. I'll push an
update when it's fixed.
