### ISSUE TITLE
mapping quality in PAF output

### ISSUE THREAD

**Issue by brunocontrerasmoreira** [ekg/wfmash#96]
Hi, I have been testing this software and parsing the produced PAF files. After checking out https://github.com/lh3/miniasm/blob/master/PAF.md I was assuming column 12 is mapping quality, but then I found this [thread](https://github.com/lh3/minimap2/issues/700#issuecomment-793564786) where it says that wfmash lacks mapping quality.
So I am confused, what's the value in column 12 then?
Thanks,
Bruno

**Comment by AndreaGuarracino** [comment]
Hi, you are right, wfmash does not yet support mapping quality, and the values output in column 12 are very inaccurate approximations of that, put there as temporary placeholders. Sorry for the confusion.
